services:
  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    container_name: auth
    restart: "no"
    ports:
      - 5005:5005
    depends_on:
      - mysql
    networks:
      - myNetwork


  # nginx:
  #   build: ./nginx
  #   restart: always
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #   networks:
  #     - myNetwork


  mysql:
    image: mysql:latest
    restart: "no"
    container_name: mysql
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_USER: username
      MYSQL_PASSWORD: passwd
      MYSQL_ROOT_PASSWORD: rootpaswd
    ports:
      - "3306:3306"
    volumes:
        - ./mysql/data:/var/lib/mysql
        # - ./mysql/sql:/docker-entrypoint-initdb.d
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge